<?php
include_once('../config/symbini.php');
header('Content-Type: text/html; charset=' . $CHARSET);
?>
<html>
	<head>
		<title>Sample Analysis</title>
		<?php
		include_once($SERVER_ROOT.'/includes/head.php');
		?>
	</head>
	<body>
		<!-- This is inner text! -->
		<div id="innertext">
			<article>
				<h1>Sample Analysis</h1>
				<h2>NEON Biorepository Sample API</h2>
				<p>The NEON Biorepository Sample API (Application Programming Interface) can be used to quickly access data as well as information about our collections, samples, and taxonomy. This API provides a simple means of constructing URLs or cURL statements that return information in a common machine-readable format, <a href="https://json.org/json-en.html">JSON (JavaScript Object Notation)</a>.</p>
				<p>The API provides numerous endpoints, some of which provide the option to enter values for specific parameters that allow you to refine your search. To learn more about each endpoint and to try each endpoint out, open the <a href="<?php echo $CLIENT_ROOT; ?>/api/v2/documentation">REST API Explorer</a>.
				</p>
				<p>For access to broader NEON data, including ecological and environmental measurements, check out the <a href="https://data.neonscience.org/data-api/">NEON Data API</a>.</p>
				<h2>Sample Explorer</h2>
				<p>NEON collects and archives up to 120,000 samples per year at the NEON Biorepository. Additional samples are collected for destructive analysis at the NEON Domain Support Facilities or external laboratories. To track samples moving between facilities, NEON generates shipment manifests and standardized receipt forms that enable NEON to track the location of a sample through its lifetime from generation in the field to final disposition. Because of the use of barcodes and autogenerated shipment manifests, NEON has greatly reduced the opportunity for transcription errors associated with labels and sample transfer. A sample's custody and location history, as well as relationships to other samples (parent, child, and siblings) can be explored using the <a href="https://data.neonscience.org/sample-explorer">Sample Explorer</a>. At the Biorepository, samples are curated following best museum practices to ensure findability within the collections.</p>
				<img src="<?php echo $CLIENT_ROOT . '/images/card-images/2020_10_SampleViewer_Table_Screenshot_1.jpg'; ?>" style="max-width:100%; max-height:100%; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);" alt="Sample Explorer" loading="lazy">
				<figcaption style="background: #F5F6F7; font-size: 15px;">Sample search results for ABBY.20170420.R0188.E; this is a mammal ear punch sample that was collected at ABBY, brought to the domain facility D16 and then shipped to CCDB for pathogen testing.</figcaption>
				<p>The NEON Sample Explorer also allows users to explore the relationship between a sample from the field and all downstream subsamples and mixtures. For example, a female Peromyscus leucopus (NEON.MAM.D01.L0253) was captured at the HARV site in 2013 on multiple dates. Using this tool, a user can see all subsamples from this mammal – in this case 3 fecal samples, 2 blood samples, 2 hair samples, and 1 ear tissue collection.</p>
				<img src="<?php echo $CLIENT_ROOT . '/images/card-images/2020_10_SampleViewer_Graph_Screenshot_0.jpg'; ?>" style="max-width:100%; max-height:100%; box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4);" alt="Sample Explorer" loading="lazy">
				<figcaption style="background: #F5F6F7; font-size: 15px;">Sample graph showing 8 subsamples (ear, hair, blood, feces) collected from small mammal NEON.MAM.D01.L0253.</figcaption>
			</article>
		</div>
	</body>
</html>